### PR TITLE
use prometheus library

### PR DESCRIPTION
**Pull request by sed-i**
This is an upkeep PR:
- usage of the prometheus_scrape library instead of rolling its own "jobs" parser
- reorg tox and tests

### CODE REVIEW

**Review by mmanciop — CHANGES_REQUESTED** [review]
This PR breaks the capability of jobs to be updated as configurations change _after_ the relation with Prometheus is established. Also, this code triggered by the `MetricsEndpointProvider` has no meaning for this charm:

```
relation.data[self._charm.unit]["prometheus_scrape_host"] = str(
    self._charm.model.get_binding(relation).network.bind_address
)
```

**Comment by mmanciop** [comment]
Just to give you an idea of just how OFF we are even after we massage the Prometheus lib vigorously to be able to update the scrape jobs when they should:

```
- {'scrape-jobs': [{'job_name': 'external_jobs',
-                   'metrics_path': '/foometrics',
-                   'static_configs': [{'labels': {'lfoor': 'lbar'},
-                                       'targets': ['foo:1234', 'bar:5678']}]}]}
+ {'scrape_jobs': '[{"metrics_path": "/metrics"}]',
+  'scrape_metadata': '{"model": "lma", "model_uuid": '
+                     '"e40bf1a0-91f4-45a5-9f35-eb30fd010e4d", "application": '
+                     '"prometheus-scrape-target"}'}
```

**Comment by balbirthomas** [comment]
>     * usage of the prometheus_scrape library instead of rolling its own "jobs" parser
1. This charm intentionally avoided the use of the Prometheus scrape library. A message to this effect was explicitly posted to the observability channel. 
2. What is the purpose of the organization ?
3. Please create a PR removing re-organization and inclusion of Prometheus library.

**Review by balbirthomas — CHANGES_REQUESTED** [review]
Please see my comments.

**Comment by sed-i** [comment]
>     2. What is the purpose of the organization ?

Before this change, the charms wasn't working: self.model.uuid was raising an attribute error. 

>     3. Please create a PR removing re-organization and inclusion of Prometheus library.

That's exactly what this PR is doing

**Comment by balbirthomas** [comment]
> Before this change, this charm wasn't working: self.model.uuid was raising an attribute error

Doesn't `model` expose a `uuid` ?

> 3. Please create a PR removing re-organization and inclusion of Prometheus library.

> That's exactly what this PR is doing
Isn't this PR adding the Prometheus charm library ? Is the library really needed to fix the `uuid` problem ?

**Comment by sed-i** [comment]
prom lib does not yet support this kind of a topology. Closing.

**Pull request closed without merging**
